### PR TITLE
Add dockerTimeout

### PR DESCRIPTION
**Pull request by dapplion**
What would be a sensible value for the max timeout? It should leave enough time for Geth to store pending states in memory.

**MUST** make sure that signals propagate correctly beforehand

Related to https://github.com/dappnode/DAppNodePackage-geth/pull/13
From https://github.com/dappnode/DNP_DAPPMANAGER/issues/420

### CODE REVIEW

**Comment by pablomendezroyo** [comment]
@dapplion can close this PR?

**Comment by dapplion** [comment]
> @dapplion can close this PR?

No! Actually all Geth nodes should have this timeout option. In Geth mainnet it's 20min even. Please ask Edu for recommended values for each testnet and add to all

https://github.com/dappnode/DAppNodePackage-geth/blob/7fefa1d1087ea7ef5f803e9dbcb684c8f9c228d0/dappnode_package.json#L12

**Comment by alexpeterson91** [comment]
@dapplion can we close this PR now?

**Comment by dapplion** [comment]
> > @dapplion can close this PR?
> 
> No! Actually all Geth nodes should have this timeout option. In Geth mainnet it's 20min even. Please ask Edu for recommended values for each testnet and add to all
> 
> https://github.com/dappnode/DAppNodePackage-geth/blob/7fefa1d1087ea7ef5f803e9dbcb684c8f9c228d0/dappnode_package.json#L12

Have these items been completed?

**Comment by alexpeterson91** [comment]
> > > @dapplion can close this PR?
> 
> > 
> 
> > No! Actually all Geth nodes should have this timeout option. In Geth mainnet it's 20min even. Please ask Edu for recommended values for each testnet and add to all
> 
> > 
> 
> > https://github.com/dappnode/DAppNodePackage-geth/blob/7fefa1d1087ea7ef5f803e9dbcb684c8f9c228d0/dappnode_package.json#L12
> 
> 
> 
> Have these items been completed?

Idk need to check and is this for CL clients as well as EL?  Regardless I think this issue should be transferred out of this repo since it's long since been fixed here.

**Pull request closed without merging**
